### ISSUE TITLE
Support for setting attribute values via data-th-attr

### ISSUE THREAD

**Issue by bcostea** [trabe/thymeleaf-rb#3]
There are some things that require the ability to set attribute values, such as input placeholder and validation attributes.
The standard th:attr="name=#{value}" notation should suffice.
I'll be working to implement this and I'll submit a pull request.

**Comment by bcostea** [comment]
I see that the default processor sort of does this but it ends up concatenating the existing value with the evaluated value.
```
node[key] = [node[key], EvalExpression.parse(context, attribute.value)].compact.join(' ')
```
Any reason for the concatenation?

**Comment by danibranas** [comment]
Hi @bcostea!
The concatenation was included for some use cases (with `class` attribute) on initial implementations. Following the original Thymeleaf engine definition, it must be an overwriting instead a concatenation, so this issue can be marked as a bug.
Thanks!

**Comment by bcostea** [comment]
Hey @danibranas, I can fix it, add a test and submit a pull request. Don't wanna take up more of your time than it's worth.

**Comment by davidbarral** [comment]
That would be very much appreciated @bcostea 😃
